import test from "node:test";
import assert from "node:assert/strict";

import { buildSeedModule } from "./refresh-seed.js";

const status = {
  updated: "2026-09-19T09:00:00.000Z",
  startDate: "06-18",
  dates: ["09-18", "09-19"],
  currentStatus: { "claude.ai": "r" },
  claudeDaily: { "claude.ai": "gr" },
  openaiDaily: { ChatGPT: "gg" },
  githubDaily: { Actions: "gg" },
  uptime: { "claude.ai": 99.5 },
  oaiIncidents: { "09-19": ["Login errors"] },
  githubIncidents: {},
  claudeMinutes: { "09-19": 30 },
  claudeDetails: { "claude.ai": { "09-19": { partialMinutes: 30 } } },
  openaiDetails: { ChatGPT: { "09-19": { titles: ["Login errors"] } } },
  githubDetails: { Actions: {} },
};

async function load(source) {
  const mod = await import(`data:text/javascript,${encodeURIComponent(source)}`);
  return mod.SEED_DATA;
}

test("builds a loadable seed module from status data", async () => {
  const seed = await load(buildSeedModule(status));

  assert.equal(seed.updated, status.updated);
  assert.deepEqual(seed.dates, status.dates);
  assert.deepEqual(seed.claudeDaily, status.claudeDaily);
  assert.deepEqual(seed.openaiDaily, status.openaiDaily);
  assert.deepEqual(seed.oaiIncidents, status.oaiIncidents);
  assert.deepEqual(seed.uptime, status.uptime);
});

test("leaves live-only state empty so a stale snapshot is not shown as current", async () => {
  const seed = await load(buildSeedModule(status));

  assert.deepEqual(seed.currentStatus, {});
  assert.deepEqual(seed.claudeDetails, {});
  assert.deepEqual(seed.openaiDetails, {});
  assert.deepEqual(seed.githubDetails, {});
});

test("marks the module as generated", () => {
  assert.match(buildSeedModule(status), /Generated by scripts\/refresh-seed\.js/);
});
