#!/usr/bin/env node
// Regenerates src/data.js (the offline fallback shown when status.json and the
// browser cache are both unavailable) from the current public/data/status.json.
// Run `npm run fetch && npm run seed` to refresh it.

import { readFileSync, writeFileSync } from 'fs';
import { pathToFileURL } from 'url';

const STATUS_PATH = 'public/data/status.json';
const SEED_PATH = 'src/data.js';

const COPIED_KEYS = [
  'updated',
  'startDate',
  'dates',
  'claudeDaily',
  'openaiDaily',
  'githubDaily',
  'uptime',
  'oaiIncidents',
  'githubIncidents',
  'claudeMinutes',
];

// A stale snapshot must not read as "current", and per-day details would bloat
// the bundle, so these stay empty.
const EMPTY_KEYS = ['currentStatus', 'claudeDetails', 'openaiDetails', 'githubDetails'];

export function buildSeedModule(status) {
  const seed = {};
  for (const key of COPIED_KEYS) seed[key] = status[key];
  for (const key of EMPTY_KEYS) seed[key] = {};

  return [
    '// Seed / fallback data — used when /data/status.json is unavailable',
    '// and no cached snapshot exists in localStorage.',
    '// Generated by scripts/refresh-seed.js from public/data/status.json. Do not edit by hand.',
    '',
    `export const SEED_DATA = ${JSON.stringify(seed, null, 2)};`,
    '',
  ].join('\n');
}

function main() {
  const status = JSON.parse(readFileSync(STATUS_PATH, 'utf8'));
  writeFileSync(SEED_PATH, buildSeedModule(status));
  console.log(`Wrote ${SEED_PATH} from ${STATUS_PATH} (updated ${status.updated})`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
