// Seed / fallback data — used when /data/status.json is unavailable
// and no cached snapshot exists in localStorage.
// Generated by scripts/refresh-seed.js from public/data/status.json. Do not edit by hand.

export const SEED_DATA = {
  "updated": "2026-09-19T09:28:19.136Z",
  "startDate": "06-22",
  "dates": [
    "06-22",
    "06-23",
    "06-24",
    "06-25",
    "06-26",
    "06-27",
    "06-28",
    "06-29",
    "06-30",
    "07-01",
    "07-02",
    "07-03",
    "07-04",
    "07-05",
    "07-06",
    "07-07",
    "07-08",
    "07-09",
    "07-10",
    "07-11",
    "07-12",
    "07-13",
    "07-14",
    "07-15",
    "07-16",
    "07-17",
    "07-18",
    "07-19",
    "07-20",
    "07-21",
    "07-22",
    "07-23",
    "07-24",
    "07-25",
    "07-26",
    "07-27",
    "07-28",
    "07-29",
    "07-30",
    "07-31",
    "08-01",
    "08-02",
    "08-03",
    "08-04",
    "08-05",
    "08-06",
    "08-07",
    "08-08",
    "08-09",
    "08-10",
    "08-11",
    "08-12",
    "08-13",
    "08-14",
    "08-15",
    "08-16",
    "08-17",
    "08-18",
    "08-19",
    "08-20",
    "08-21",
    "08-22",
    "08-23",
    "08-24",
    "08-25",
    "08-26",
    "08-27",
    "08-28",
    "08-29",
    "08-30",
    "08-31",
    "09-01",
    "09-02",
    "09-03",
    "09-04",
    "09-05",
    "09-06",
    "09-07",
    "09-08",
    "09-09",
    "09-10",
    "09-11",
    "09-12",
    "09-13",
    "09-14",
    "09-15",
    "09-16",
    "09-17",
    "09-18",
    "09-19"
  ],
  "claudeDaily": {
    "Claude API": "ooyyyyyyyyyyygyoyoyggygyooggyrygyooogroyggyoyggggggyoogoyyyogggoggggggggooggggggyogggogggg",
    "claude.ai": "ooyyyyyyyyyyygroyoyggyoyooggyryyyooogroyggyoyggggggyoooryyyogggoggggggyyoogggggggogggogggg",
    "Claude Code": "ooyyyyyyyyyyygyoyoyggygyooggyryyyooogroyggyoyggggggyoogryyyogggogggoggygoogggggggogggogggg",
    "platform.claude.com": "goygggggyggyggggggyggygyooggyrygygogggggggyygggggggggggrgggggggggggggggyyggggggggggggggggg",
    "Claude Cowork": "ooyyyyyyyyyyygyoyoyggygyooggyrygyooogroyggyoyggggggyoogryyyogggogggoggggooggggggyyyyyogggg",
    "Claude for Government": "ggggggggyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"
  },
  "openaiDaily": {
    "OpenAI APIs": "ggyggggggggggggggggggggggggggggygygygygggggggggggggggggggggggggggggggggggggggggggygggggygg",
    "ChatGPT": "gggyyyygggggggggggggygoogggogggygyggggyggggyyggggyygyggggggygggggggggggygoyggggyyggygygggg",
    "Codex": "gggyygggggggggggggggggggggggyggyyygggggggggggggggggggggggggggggggggggggggyyggggggggggggggg",
    "Sora": "ggyggggggggggggggggrgggggggggggygygggggggggggggggggggggggggggggggggggggggggggggggggggggygg",
    "FedRAMP": "yyyyyggyyyyyyyyyyyyygggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"
  },
  "githubDaily": {
    "GitHub API": "ggggggggggggggggggggggggyygyogggyggyggggggggggggggygggggrggggggggggggggggggggggggggygggggg",
    "Git Operations": "ggggggggggggggggggggggggggggggggggggggggggggggggggggygggyggggggggggggggggggggggggggggggggg",
    "Actions": "gggogggggggggggygrgggogggggyogyoorgggogggggggrrgggggggggrggggggygryggggggggggggggggygggggg",
    "Copilot": "gggggggggyggggggggggggggggggggggygggggggggygggggggggggggrggggggggggggggggggggggggggggggggg",
    "Webhooks": "gggyggggggggggggggggggyggggggggyggggggggggggggggggggygggoggggggggggggggggggggggggggggggggg",
    "Issues": "gggygggggggggggggggggggggggyyggyyggggggggggggggggggyygggrggggggggggggggggggggggggggygggggg",
    "Pull Requests": "gggygggggggggggggggggggggggggggyrggggggggggggggggggyygggrggggggggyyggggygggggggggggrgggggg",
    "Packages": "ggggggggggggggggggggggggggggggggggggggggggggggggggggyggggggggggggggggggggggggggggggggggggg",
    "Pages": "ggggggggggyggggggygggygggggyygggyggggggggggggrrgggggggggyggggggggygggggggggggggggggygggggg",
    "Codespaces": "gggggggggggggggoggggggyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    "Copilot AI Model Providers": "ggggggggggggggggggggggggygggyggggogggyygygggggggggggyggggggggggoggrgggyggygggggggggggyoygg"
  },
  "uptime": {
    "claude.ai": 99.4,
    "platform.claude.com": 99.93,
    "Claude API": 99.49,
    "Claude Code": 99.43,
    "Claude Cowork": 99.42,
    "Claude for Government": 100,
    "OpenAI APIs": 99.93,
    "ChatGPT": 99.63,
    "Codex": 100,
    "Sora": 99.97,
    "FedRAMP": 100,
    "Git Operations": 100,
    "Webhooks": 99.99,
    "GitHub API": 99.86,
    "Issues": 99.89,
    "Pull Requests": 99.83,
    "Actions": 99.25,
    "Packages": 100,
    "Pages": 99.65,
    "Copilot": 99.68,
    "Codespaces": 99.97,
    "Copilot AI Model Providers": 99.84
  },
  "oaiIncidents": {
    "09-19": [
      "Overbilling for OpenAI-hosted containers in the Agent API"
    ],
    "09-18": [
      "SSO sign-in and SCIM provisioning issues"
    ],
    "09-17": [
      "We are seeing elevated error rates across API models",
      "Elevated errors affecting ChatGPT Work mode"
    ],
    "09-16": [
      "Elevated errors in ChatGPT Work",
      "Elevated errors with gpt-image-2.5-flare"
    ],
    "09-15": [
      "Ads Manager login issues",
      "Elevated errors from GPT-5.6 and GPT-5.6 Instant on paid plans",
      "Elevated errors affecting Work Mode in ChatGPT"
    ],
    "09-14": [
      "Degraded Performance affecting Agents API",
      "Elevated error rates for Codex and ChatGPT Work"
    ],
    "09-13": [
      "Elevated errors for ChatGPT users in Europe",
      "Codex GitHub Review and Pull Request Failures"
    ],
    "09-12": [
      "1% of ChatGPT Work (mobile/web) turns are failing for existing threads"
    ],
    "09-11": [
      "Elevated errors for GPT-5.6 Sol on the API",
      "Elevated errors for ChatGPT users in Europe"
    ],
    "09-10": [
      "Elevated errors affecting ChatGPT Work",
      "Unable to open shared ChatGPT Project using direct link"
    ],
    "09-09": [
      "Increased Error Rate For Pro and Plus Plan Conversations"
    ],
    "09-08": [
      "Elevated errors for image generation",
      "File uploads are delayed or failing"
    ],
    "09-04": [
      "Users in APAC region may face increased error in ChatGPT, Work, image generation, file upload, Voice, and Codex Cloud"
    ],
    "09-03": [
      "Elevated errors across ChatGPT and Codex",
      "ChatGPT Work Mode High Error Rates"
    ],
    "09-01": [
      "Elevated latency in the Responses API",
      "Elevated errors in ChatGPT conversations for Free and Go plans"
    ],
    "08-31": [
      "ChatGPT Work seeing elevated errors and latency"
    ],
    "08-27": [
      "Users may experience an increase in error rates in Workspace Agents and ChatGPT Work on Web and Mobile"
    ],
    "08-21": [
      "Unexpected logouts for some ChatGPT web users"
    ],
    "08-20": [
      "Elevated Codex API authentication errors",
      "Elevated Errors for Thinking mode in ChatGPT",
      "Chatgpt.com is down - all signups and logins are down as of right now"
    ],
    "08-18": [
      "Elevated errors deploying Sites"
    ],
    "08-13": [
      "Elevated errors in ChatGPT conversations for Free users"
    ],
    "08-11": [
      "Increase in errors on API, Codex and Work Mode",
      "Users unable to login to ads manager",
      "Increased error rates",
      "Elevated errors affecting ChatGPT Go conversations"
    ],
    "08-10": [
      "Increased errors for some ChatGPT users"
    ],
    "08-05": [
      "Elevated errors with image generation",
      "Issues with Custom GPT actions",
      "Elevated errors in ChatGPT conversations with files"
    ],
    "08-04": [
      "Elevated ChatGPT conversation errors affecting Plus, Pro, Business, and Edu users"
    ],
    "07-30": [
      "Elevated errors affecting ChatGPT conversations"
    ],
    "07-29": [
      "Elevated error rates with the invalid_prompt error code"
    ],
    "07-28": [
      "Elevated Image Generation Error Rate in ChatGPT"
    ],
    "07-27": [
      "Image generation unavailable in ChatGPT",
      "We’re seeing elevated latency, timeouts, and interrupted streaming across gpt 5.1 mini model and gpt 4.1 mini",
      "Elevated errors affecting ChatGPT conversations"
    ],
    "07-25": [
      "Elevated error rates"
    ],
    "07-24": [
      "Elevated Error Rates",
      "Elevated Errors in Codex Review",
      "Elevated API error rates and latency on gpt-image-2 model"
    ],
    "07-23": [
      "Some users may experience elevated error rates in ChatGPT"
    ],
    "07-22": [
      "Elevated errors for Workspace Agent",
      "Elevated Errors Affecting File Uploads and Image Generation"
    ],
    "07-21": [
      "Elevated errors for API image generation",
      "Issues with logins and signups"
    ],
    "07-20": [
      "Elevated errors for GitHub-dependent ChatGPT and Codex workflows"
    ],
    "07-19": [
      "Elevated errors affecting ChatGPT"
    ],
    "07-18": [
      "Some users are unable to access Codex",
      "New ChatGPT App Not Available For Enterprise Users Without Codex Permissions"
    ],
    "07-17": [
      "Codex 5.6-sol Experiencing Increased Server-Overload Errors",
      "Elevated errors for Github connector"
    ],
    "07-16": [
      "Elevated Error Rates For SSO Login"
    ],
    "07-15": [
      "Elevated errors affecting ChatGPT",
      "Issue affecting voice mode in ChatGPT"
    ],
    "07-14": [
      "Some ChatGPT Go users may experience conversation failures when using GPT-5.5."
    ],
    "07-13": [
      "Users may experience elevated errors uploading, deleting, and navigating files in the ChatGPT Library",
      "Elevated errors when creating sites in ChatGPT"
    ],
    "07-12": [
      "Elevated conversation and login errors on ChatGPT for iOS and macOS"
    ],
    "07-07": [
      "Elevated errors with image generation in ChatGPT"
    ],
    "06-29": [
      "Codex Usage Limits Depleting Faster Than Expected"
    ],
    "06-28": [
      "Issues with ChatGPT Windows desktop app"
    ],
    "06-26": [
      "Small Number of Users Have Incorrectly Cancelled Subscription"
    ],
    "06-25": [
      "Users may encounter issues using access token with Codex"
    ],
    "06-24": [
      "gpt-4o-mini high error rate"
    ],
    "06-23": [
      "Users may experience elevated errors in ChatGPT uploading and downloading files"
    ]
  },
  "githubIncidents": {
    "07-20": [
      "Incident with GitHub Actions"
    ],
    "08-17": [
      "Incident with GitHub.com"
    ],
    "06-25": [
      "Degradation with Webhooks, Pull Requests and Actions"
    ],
    "07-09": [
      "Delays starting Actions runs"
    ],
    "07-13": [
      "Actions runs are experiencing failures to start"
    ],
    "07-23": [
      "Latency issues across a number of services"
    ],
    "07-24": [
      "Disruption with some GitHub services"
    ],
    "07-25": [
      "Incident with Actions",
      "Actions run failures and delays"
    ],
    "07-29": [
      "Incident with Actions"
    ],
    "08-06": [
      "Incident with Actions"
    ],
    "08-07": [
      "Incident with Actions"
    ],
    "08-26": [
      "Incident with Actions",
      "Incident with Actions and Pull Requests"
    ]
  },
  "claudeMinutes": {
    "06-22": 267,
    "06-23": 255,
    "07-06": 27,
    "07-07": 354,
    "07-09": 66,
    "07-14": 45,
    "07-16": 678,
    "07-17": 75,
    "07-21": 317,
    "07-25": 294,
    "07-26": 18,
    "07-27": 3,
    "07-29": 453,
    "07-30": 738,
    "08-04": 51,
    "08-13": 415,
    "08-14": 51,
    "08-15": 21,
    "08-16": 105,
    "08-20": 78,
    "08-24": 612,
    "09-02": 81,
    "09-03": 561,
    "09-11": 27,
    "09-15": 258,
    "08-28": 102
  },
  "currentStatus": {},
  "claudeDetails": {},
  "openaiDetails": {},
  "githubDetails": {}
};
